const BAD_REQUEST = 400;
const NOT_FOUND = 404;
const DEFAULT = 500;
const NOT_AUTHORIZED = 401;
const NOT_OWNER = 403;
const DUPLICATE_EMAIL = 409;

module.exports = {
  BAD_REQUEST,
  NOT_FOUND,
  DEFAULT,
  NOT_AUTHORIZED,
  NOT_OWNER,
  DUPLICATE_EMAIL,
};
